### ISSUE TITLE
Planning: September meetup

### ISSUE THREAD

**Issue by ncoghlan** [BrisPy/brispy-admin#7] opened 2017-08-14 08:11 UTC
# Brisbane Python User Group meetup checklist

- [x] choose day (Wednesday 13th September)
- [x] choose venue (current default: Red Hat level 3)
- [x] choose topics/find speakers:
     - Anna Gerber (@AnnaGerber): [IoT development with MicroPython](https://pycon-au.org/schedule/presentation/93/)
     - Fraser Tweedale (@frasertweedale): [Social & Federated Authentication](https://2017.pycon-au.org/schedule/presentation/37/)
- [x] announce on MeetUp (requires organiser access to the MeetUp group)
- [x] book the venue/meeting room
- [x] arrange food sponsorship (no current default)
- [x] preorder food (see current default pizza order below)
- [x] check waitlist numbers the week of the meetup and post MeetUp comment to remind folks to adjust their RSVP if they can't make it
- [x] post MeetUp comment to thank attendees, speakers & sponsors and provide a pointing to the talks repo to both request and offer talks
- [x] file the admin issue for the next month's MeetUp

## Meetup announcement notes:

- usual start time when hosting in the CBD is 5:30 PM for a 5:45 PM start. Add 15 minutes if hosting outside the CBD (e.g. at the State Library)
- mention the day & date in the meeting title (MeetUp's UI doesn't make it very prominent otherwise)
- thank both the venue sponsor and the food sponsor

## Speaker organisation notes:

- use the talks repo, that's what it's for :)
- the PyCon Australia schedule can also be a good resource for finding folks that are local to Brisbane and willing to talk about Python in public
- we aim for talks to run for 25-30 minutes, including time for questions (not coincidentally, this is also a typical PyCon AU timeslot)
- make sure speakers know which of them is speaking first
- make sure speakers have a mobile contact number for at least one of the organisers

## Meetup notes:

- explain the general plan for the evening (first talk, food, second talk)
- cover venue logistics in initial introduction (bathroom locations, fire exits)
- if the venue has guest wi-fi, make sure you know the password

Default food order is 15 Dominos pizzas for delivery at 6:15 pm:

- 3x Supreme
- 2x Chicken and Feta
- 2x Chili Pork
- 2x Lamb Tzatziki
- 2x Loaded Meatlovers
- 2x Vegorama
- 1x Supreme on gluten free base
- 1x Vegorama on gluten free base

**Comment by ncoghlan** [comment] 2017-08-14 08:18
Note: I'll be away at the CPython core dev sprints in San Francisco for the first week of September, so I won't actually be at the meetup this month.

@elusivenode has a possible venue down at Eagle St if we wanted to try that as an alternative to the Red Hat office: https://github.com/BrisPy/brispy-admin/issues/1#issuecomment-321239196

@danc86 @clintonroy What do you think? Red Hat again in September, then Eagle St in October? Or try Eagle St in September?

**Comment by danc86** [comment] 2017-08-14 08:45
I am also overseas for the next meetup so if anyone from Red Hat is hosting it would have to be @romanofski or @anchat1990.

**Comment by anchat1990** [comment] 2017-08-14 10:21
Ah unfortunately I am on leave as well from Monday 4th - Wednesday 6th September. I can still arrange food for the night beforehand. I think that leaves only @romanofski , would it be very difficult to change to the second week?

**Comment by ncoghlan** [comment] 2017-08-14 11:29
Second week would be feasible, especially since August was also in the 2nd week (I belatedly realised that's why the preparation period for September felt so short).

If we do that, I'd be inclined to just amend the template to make the 2nd Wednesday the default from now on, since that generally works better in January as well.

**Comment by frasertweedale** [comment] 2017-08-14 11:52
I'm available either week, but would prefer the 6th.  Also, if I'm speaking it does mean another Red Hatter will be there :)

**Comment by romanofski** [comment] 2017-08-15 07:10
I'm also available either week and happy to jump in if no one is able to organize :)

**Comment by ncoghlan** [comment] 2017-08-22 12:10
@romanofski If you could take over organising for September, that would be great :)

At this point, I'm wondering if it may be worth making it second week just because we've slipped so late into August without announcing the September meeting (assuming the 13th still works for @frasertweedale and @AnnaGerber, of course).

**Comment by romanofski** [comment] 2017-08-25 07:54
I've got a positive from @frasertweedale for the 13th of September, but I'm still missing any feedback from @AnnaGerber. @ncoghlan Could you perhaps ping her with other means than github?

**Comment by AnnaGerber** [comment] 2017-08-25 08:24
Yes confirmed, sorry, this week has been hectic

**Comment by romanofski** [comment] 2017-08-25 10:52
Sweet. Cheers!

**Comment by romanofski** [comment] 2017-08-28 00:06
@ncoghlan In regards to the catering, do we already have a sponsor?

**Comment by anchat1990** [comment] 2017-08-28 00:53
@kaiw @clintonroy , @danc86 was mentioning that Bloomberg was going to cover this months sponsorship - would you be able to confirm this?

**Comment by kaiw** [comment] 2017-08-28 21:58
Yes, this is sorted. However, as we're still sorting out the situation we have a limited budget this time around (though will still cover the default pizza order). I'm hoping that we'll be able to sort out something more permanent soon.

**Comment by romanofski** [comment] 2017-08-29 08:14
Cool! I'll prepare the announcement then...

**Comment by kaiw** [comment] 2017-09-12 23:20
@romanofski Can you let us know what's happening with the food order? I'm assuming that it's going to be the default Dominos order, but we haven't arranged anything.

**Comment by romanofski** [comment] 2017-09-13 00:37
@kaiw Use the default Dominos order. I have nothing else.

**Comment by kaiw** [comment] 2017-09-13 03:07
Sorry, but I don't have enough details to do this at the moment. What address (floor, etc.) do I provide for the order? and whose mobile number should I provide? (since I can't actually let anyone in to the building)

I've never done any ordering for this meetup before, so I'm clueless here.

**Comment by anchat1990** [comment] 2017-09-13 03:39
@kaiw We usually give them the address: Lobby, 193 N Quay, Brisbane. @ncoghlan or @romanofski will have to let them in as Im no longer able to make it tonight (flu) - so it will have to be one of their mobile numbers

**Comment by romanofski** [comment] 2017-09-13 03:43
@kaiw send you a meetup message with my phone number.

**Comment by ncoghlan** [comment] 2017-09-13 03:47
@romanofski Even though I'm in town, I won't actually be there tonight - since I thought it was already geld last week while I was away, I ended up with family commitments this evening (my sister is in town, and I didn't arrange a different night to catch up, since I thought tonight was free).

**Comment by romanofski** [comment] 2017-09-13 23:54
@ncoghlan no worries. Went all well (except that we lost the light on Lvl3 mid-flight, but got it back on).

**Comment by romanofski** [comment] 2017-09-14 00:04
Alright #8 is up... any takers? ;) Closing this one.

**Closed as completed by romanofski** 2017-09-14 00:04 UTC
